### ISSUE TITLE
Unable to install stripnet

### ISSUE THREAD

**Issue by kpkhushi15** [stephenleo/stripnet#7]

**Comment by kpkhushi15** [comment]
![Screenshot 2022-02-10 at 5 11 51 PM](https://user-images.githubusercontent.com/41112985/153402091-161414af-782a-44c1-a203-818341da11d1.png)

**Comment by stephenleo** [comment]
Hi can I check which version of Python you are using? There's an issue with hdbscan that can only work with Python 3.8 and above.

**Comment by kpkhushi15** [comment]
Currently I am using python 3.7

**Comment by kpkhushi15** [comment]
I tried installing with Python 3.8 as well but same issue.

**Comment by kpkhushi15** [comment]
Now I am able to install it on Python 3.8 but getting "SSL certificate verify failed". (_ssl.c:1123)

**Comment by stephenleo** [comment]
Great news you're able to install on Python 3.8!

For the latest error, can you share a screenshot of which line of code generates the error?

**Comment by kpkhushi15** [comment]
when i am trying to run this command "stripnet=StripNet()", here I am getting "SSL certificate verify failed". (_ssl.c:1123) error. 
It says that unable to get local issuer certificate (_ssl.c:1123).

When I run "stripnet=StripNet()", first thing i get is "Load pretrained SentenceTransformer: allenai-sepcter" followed with SSL error.

**Comment by stephenleo** [comment]
Ok this is most likely an issue with your network. Stripnet needs to download the `allenai-specter` pre-trained model for sentence transformers to work. The model is hosted by Allen AI and your network might be blocking it for some reason. You could try running the below 2 lines of code to replicate the issue without even touching stripnet.

Is your computer having a VPN or network restrictions? Normally laptops issued by some companies have download restrictions that could cause this. If you're trying to get it to work on a work computer, please get in touch with your IT on how to bypass the error and download the model.


Minimum code example to replicate the issue:
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('allenai-specter')
```

**Comment by kpkhushi15** [comment]
Yes, I am trying it on my work laptop and connected with VPN. This might be causing it probably.

**Comment by kpkhushi15** [comment]
I tried the minimal code which you have mentioned in your reply but its not working.

**Comment by stephenleo** [comment]
Yes then it's confirmed your work laptop VPN blocking the connection to download the `allenai-specter` model. Unfortunately you'll have to find some way to download the model offline and move it onto your computer.

https://huggingface.co/sentence-transformers/allenai-specter
